### ISSUE TITLE
Working on Live Demo but not working from my machine on Chrome(Chrome Version  42.0.2311.90 m)

### ISSUE THREAD

**Issue by BhartiYadav** [tmcw/simple-statistics#93]

**Comment by tmcw** [comment]
Can you be a little more specific? which live demo?

**Comment by stevemandl** [comment]
I'm running Version 43.0.2357.65 (64-bit) and I get this error when I try to include it in a page:

Uncaught TypeError: Cannot set property 'ss' of undefined(anonymous function) @ simple_statistics_m.js:21(anonymous function) @ simple_statistics_m.js:1574

**Comment by tmcw** [comment]
Please provide a link, otherwise this is not diagnosable.

**Comment by NerdYouDontKnow** [comment]
Same issue here.

Strict mode was enabled in ae58d1e975425127d23627564c9bf300b74dec9a. The problem is, [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#.22Securing.22_JavaScript) doesn't let you access the window object through `this`, so it can't set `ss`. However, there are [workarounds](http://stackoverflow.com/questions/7290086/javascript-use-strict-and-nicks-find-global-function) that can be implemented.

I just removed `'use strict';` from my copy and it works fine now.
